### ISSUE TITLE
ExpViewer disappears, needs "reappear" function/hotkey

### ISSUE THREAD

**Issue by iBaer** [Excrulon/Tree-of-Savior-Addons#61] opened 2016-04-28 21:12 UTC
The ExpViewer disappears for me if I push "Esc" to open the options, or if I change the map.
There doesn't seem to be a way to make it reappear manually yet, is there?

**Comment by Excrulon** [comment] 2016-04-28 21:14
For now, if you kill something that gives exp, it should reappear. Will add
in a fix later.

**Comment by iBaer** [comment] 2016-04-28 21:22
It doesn't (for me).
If it would just reappear when I get exp again, it wouldn't really bother me.
Only way to get it back again is to restart the game.

**Comment by iBaer** [comment] 2016-04-28 22:41
Just checked again. It's a problem that happens with the latest commit, but not with the "downloadble" version.
I'll take a look at it tomorrow, if you haven't by then.

**Comment by Excrulon** [comment] 2016-04-28 22:56
If you're using any files off the master branch and not 100% from the bundled release, make sure you have all of the latest files. Everything works fine for me. Experience viewer reappears after hud updates for me.

**Comment by iBaer** [comment] 2016-04-28 23:12
Now that's weird.
I've even made a clean "installation" with the latest files from Latest commit fc43f4d (+ the SumAni.ipf from the latest release Tag 1.7).

**Comment by mattarolla** [comment] 2016-04-29 02:01
@Excrulon Hello, I am kind of slow at Github. How do we use the latest commit to master? Do I just download the files and extract them to the game folder? Do we need a new SumAni.ipf?

**Comment by Excrulon** [comment] 2016-04-29 02:05
If you want everything, you can just go to the main page and click download zip. Automatically downloads whatever is committed to the master branch. Then you can just copy the addons folder over your old one and replace all the files. You should have all the latest stuff that way. You don't need a new SumAni.ipf if you already have it installed from the previous release. In the next release, you won't need SumAni.ipf anymore. Going to release a new bundle either tonight or tomorrow.

**Comment by Hereticide** [comment] 2016-04-30 18:15
I am having the same issue mentioned in the post.

This is especially true when I become disconnected and bounced to the login screen, but, has happened when transitioning maps as well. Reproduction is not 100% but is not remedied by killing a monster but as mentioned by manually closing the game and re-opening.

I use modified settings to only display Exp/hr and ETA to level, and re-position the box to the location where "weapon swap" would be (if I were to actually learn it lol).

I actually created a github account to report the issue but am glad someone else had it too. I was also hoping for some forced manual restart. I don't know how well you get along with Lemon, but, it could be a step in the right direction if you add a slash command officially. Would save the trouble of having to code more. Could be a simple /expshow to reload or display and /exphide to close expviewer =)

**Comment by iBaer** [comment] 2016-05-08 11:57
@Excrulon: 
I finally found the time to make some tests, and the reason, why the exp viewer doesn't reappear is really silly.

If you only try to install the master version, there is no settings.txt.
Not sure if you want this silly settings.txt to be part of the git-project. But you might either just add it, or create a function that creates one if non-existent. I could do the latter, if you want some quick help with it.

**Comment by TehSeph** [comment] 2016-05-08 15:33
... Wait is this _really_ the reason why? You guys need to read the readme on the frontpage of the repo.
```
Be sure to press the "R" button at the topright of the experience viewer window in order to save its position after moving it. It will move back if you don't.
```

**Comment by iBaer** [comment] 2016-05-08 15:50
Yes, this creates the settings file, but that's not what the frontpage says and how it should be. Definetly not.

It's not about the position resetting, it's about the expviewer **disappearing**. The settings file should therefore be created (if it doesnt exist) with the init process.

**Comment by TehSeph** [comment] 2016-05-08 18:13
> that's not what the frontpage says

I quite _literally_ copied that off the frontpage.

> it's about the expviewer disappearing.

Which clicking that button fixes. The reason it disappears is because it doesn't have a position set.

**Comment by iBaer** [comment] 2016-05-08 18:39
The frontpage doesn't say, that clicking ojn the reset-button creates the settings.txt which is a must for the expviewer not disappearing.

Yes, it is logical that the expviewer, once closed, will not reappear if it can't reload a position.
But let's be honest, how should anyone know, the (default) position isn't saved yet?
The solution is far from obvious.
If you don't have the settings.txt anymore from a previous installation or if the first thing you don't do is to reset the position (why would you, if the default position is fine?), then the situation is far from clear.

**Comment by Excrulon** [comment] 2016-05-08 19:03
I'll look into fixing this soon.

**Comment by Windrunnerex** [comment] 2016-05-19 01:34
erm mr excrulon is there a way to readjust the position as my exp viewer was set slightly out of the screen and i want to readjust it .

**Comment by Excrulon** [comment] 2016-05-19 01:42
Drag it where you want it and press the "R" button on it to lock the position for now.

**Closed** 2016-08-02 09:48 UTC
Labels: bug, enhancement
